In [5]:
import numpy as np

In [6]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

In [7]:
a+b

array([6, 6, 6, 6, 6])

In [10]:
c = [1, 2, 3]
d = [3, 2, 1]

print c
print d

[1, 2, 3]
[3, 2, 1]


In [9]:
np.add(c, d)

array([4, 4, 4])

In [12]:
np.multiply(a, b)

array([5, 8, 9, 8, 5])

In [13]:
a = [1, 2, 3, 4, 5, 6]
b = [-6, -5, -4, -3, -2, -1]

np.add(a, b)

array([-5, -3, -1,  1,  3,  5])

In [14]:
a = [-1, -2, -3, -4, -5, -6]
b = [-6, -5, -4, -3, -2, -1]

np.subtract(a, b)

array([ 5,  3,  1, -1, -3, -5])

In [15]:
a = [101, 201, 33.22, -423, 5.3234, -6.234]
b = [-601, 501.33, -113, 3.3000003, -2, -1.999999999999999]

np.subtract(a, b)

array([ 702.       , -300.33     ,  146.22     , -426.3000003,
          7.3234   ,   -4.234    ])

In [25]:
a = [-101, -201, -33.22, 423, -5.3234, -34]
b = [601, -501.33, 113, -3.3000003, '1', 10.999999999999999]

for index, value in enumerate(b):
    print index, value, type(value)
    if type(value) == str:
        print "FOUND STRING"
        b[index] = 0

#np.subtract(a, b)

0 601 <type 'int'>
1 -501.33 <type 'float'>
2 113 <type 'int'>
3 -3.3000003 <type 'float'>
4 1 <type 'str'>
FOUND STRING
5 11.0 <type 'float'>
