In [1]:
# import numpy
# create array x
import numpy as np
x = np.array([1, 2, 3])

In [2]:
# print the shape of x
x.shape

(3,)

In [29]:
# create a two dimensional array
a = np.array([[1, 2], [4, 5], [7, 8]])
print a

[[1 2]
 [4 5]
 [7 8]]


In [30]:
# print shape of 2d array
a.shape

(3, 2)

In [5]:
# reshape the array to 2 x 6

In [6]:
# reshape the array to 1 x 12

In [18]:
# transpose the array
a.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [8]:
# indexing method 1

In [9]:
# indexing method 2

In [13]:
# indexing method 3

In [12]:
# indexing method 4

In [11]:
# indexing method 5

In [10]:
# indexing method 6

Independent Practice: Topic (20 minutes)
Create 2 arrays. Add them together, subtract them, and do the dot product.
Bonus:

Create a 3 dimensional array
Create a 5 dimensional array

In [21]:
c = [1, 2, 3]
d = [4, 5, 6]

In [22]:
np.add(c, d)

array([5, 7, 9])

In [23]:
np.subtract(c, d)

array([-3, -3, -3])

In [24]:
np.dot(c, d)

32

In [27]:
e = np.array([[[1, 2, 3], [1, 2, 3], [1, 2, 3]],
              [[4, 5, 6], [4, 5, 6], [4, 5, 6]],
              [[7, 8, 9], [7, 8, 9], [7, 8, 9]]])
print e
e.shape

[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]


(3, 3, 3)

In [28]:
f = np.array([[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]],
              [[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]],
              [[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]],
              [[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]],
              [[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]])

print f
f.shape

[[[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]]


(5, 4, 3)